import { additionalServices } from "@/lib/catalog/additional-services";
import {
  PAAS_AWS_IDS,
  PAAS_AZURE_IDS,
  PAAS_CLOUD_SERVICE_IDS,
  PAAS_GCP_IDS,
} from "@/lib/catalog/paas-services";
import {
  SAAS_COMPLIANCE_IDS,
  SAAS_CYBER_IDS,
  SAAS_IT_IDS,
  SAAS_SOLUTION_IDS,
} from "@/lib/catalog/saas-segment-ids";
import type { CatalogData } from "@/types";

const none: CatalogData["services"][0]["departments"] = [];

/** Demo catalog when Supabase env vars are not set (local dev / preview). */
export const fallbackCatalog: CatalogData = {
  services: [
    {
      id: "1",
      name: "Snowflake",
      slug: "snowflake",
      description:
        "Cloud data platform for warehousing, analytics, and secure data sharing at scale.",
      category: "SaaS",
      vendor: "Snowflake Inc.",
      logo_url: "https://logo.clearbit.com/snowflake.com",
      website_url: "https://www.snowflake.com",
      tags: ["data-warehouse", "analytics", "sql"],
      departments: ["finance", "it", "engineering"],
      created_at: new Date().toISOString(),
    },
    {
      id: "2",
      name: "BigQuery",
      slug: "bigquery",
      description:
        "Serverless, highly scalable multi-cloud data warehouse built for analytics.",
      category: "SaaS",
      vendor: "Google Cloud",
      logo_url: "https://logo.clearbit.com/cloud.google.com",
      website_url: "https://cloud.google.com/bigquery",
      tags: ["data-warehouse", "analytics", "serverless"],
      departments: ["finance", "it", "engineering"],
      created_at: new Date().toISOString(),
    },
    {
      id: "3",
      name: "Amazon Redshift",
      slug: "amazon-redshift",
      description:
        "Fully managed petabyte-scale cloud data warehouse for analytics workloads.",
      category: "SaaS",
      vendor: "AWS",
      logo_url: "https://logo.clearbit.com/aws.amazon.com",
      website_url: "https://aws.amazon.com/redshift/",
      tags: ["data-warehouse", "analytics", "aws"],
      departments: ["finance", "it", "engineering"],
      created_at: new Date().toISOString(),
    },
    {
      id: "4",
      name: "Databricks",
      slug: "databricks",
      description:
        "Lakehouse platform unifying data engineering, analytics, and machine learning.",
      category: "PaaS",
      vendor: "Databricks",
      logo_url: "https://logo.clearbit.com/databricks.com",
      website_url: "https://www.databricks.com",
      tags: ["lakehouse", "spark", "ml"],
      departments: none,
      created_at: new Date().toISOString(),
    },
    {
      id: "5",
      name: "Datadog",
      slug: "datadog",
      description:
        "Observability platform for metrics, logs, traces, and security monitoring.",
      category: "SaaS",
      vendor: "Datadog",
      logo_url: "https://logo.clearbit.com/datadoghq.com",
      website_url: "https://www.datadoghq.com",
      tags: ["monitoring", "apm", "observability"],
      departments: ["it", "site-operations", "engineering"],
      created_at: new Date().toISOString(),
    },
    {
      id: "6",
      name: "Grafana Cloud",
      slug: "grafana-cloud",
      description:
        "Managed observability stack for metrics, logs, traces, and dashboards.",
      category: "SaaS",
      vendor: "Grafana Labs",
      logo_url: "https://logo.clearbit.com/grafana.com",
      website_url: "https://grafana.com/products/cloud/",
      tags: ["monitoring", "dashboards", "observability"],
      departments: ["it", "site-operations", "engineering"],
      created_at: new Date().toISOString(),
    },
    {
      id: "7",
      name: "New Relic",
      slug: "new-relic",
      description:
        "Full-stack observability with APM, infrastructure monitoring, and logs.",
      category: "SaaS",
      vendor: "New Relic",
      logo_url: "https://logo.clearbit.com/newrelic.com",
      website_url: "https://newrelic.com",
      tags: ["monitoring", "apm", "observability"],
      departments: ["it", "site-operations", "engineering"],
      created_at: new Date().toISOString(),
    },
    {
      id: "8",
      name: "Prometheus",
      slug: "prometheus",
      description:
        "Open-source systems monitoring and alerting toolkit with a dimensional data model.",
      category: "SaaS",
      vendor: "CNCF",
      logo_url: "https://cdn.simpleicons.org/prometheus/E6522C",
      website_url: "https://prometheus.io",
      tags: ["monitoring", "metrics", "open-source"],
      departments: ["it", "site-operations", "engineering"],
      created_at: new Date().toISOString(),
    },
    {
      id: "9",
      name: "Vercel",
      slug: "vercel",
      description:
        "Frontend cloud for deploying and scaling Jamstack and full-stack web apps.",
      category: "PaaS",
      vendor: "Vercel",
      logo_url: "https://logo.clearbit.com/vercel.com",
      website_url: "https://vercel.com",
      tags: ["hosting", "serverless", "edge"],
      departments: none,
      created_at: new Date().toISOString(),
    },
    {
      id: "10",
      name: "Heroku",
      slug: "heroku",
      description:
        "PaaS for building, running, and scaling applications in multiple languages.",
      category: "PaaS",
      vendor: "Salesforce",
      logo_url: "https://logo.clearbit.com/heroku.com",
      website_url: "https://www.heroku.com",
      tags: ["hosting", "paas", "containers"],
      departments: none,
      created_at: new Date().toISOString(),
    },
    {
      id: "11",
      name: "AWS EC2",
      slug: "aws-ec2",
      description:
        "Scalable virtual servers in the cloud for compute-intensive workloads.",
      category: "IaaS",
      vendor: "AWS",
      logo_url: "https://logo.clearbit.com/aws.amazon.com",
      website_url: "https://aws.amazon.com/ec2/",
      tags: ["compute", "vms", "aws"],
      departments: none,
      created_at: new Date().toISOString(),
    },
    {
      id: "12",
      name: "Google Compute Engine",
      slug: "google-compute-engine",
      description:
        "High-performance virtual machines running on Google's global infrastructure.",
      category: "IaaS",
      vendor: "Google Cloud",
      logo_url: "https://logo.clearbit.com/cloud.google.com",
      website_url: "https://cloud.google.com/compute",
      tags: ["compute", "vms", "gcp"],
      departments: none,
      created_at: new Date().toISOString(),
    },
    {
      id: "13",
      name: "Azure Virtual Machines",
      slug: "azure-virtual-machines",
      description:
        "On-demand scalable compute capacity with Windows and Linux VMs.",
      category: "IaaS",
      vendor: "Microsoft Azure",
      logo_url: "https://logo.clearbit.com/azure.microsoft.com",
      website_url: "https://azure.microsoft.com/products/virtual-machines",
      tags: ["compute", "vms", "azure"],
      departments: none,
      created_at: new Date().toISOString(),
    },
    {
      id: "14",
      name: "Stripe",
      slug: "stripe",
      description:
        "Payments infrastructure for the internet — APIs for billing and subscriptions.",
      category: "SaaS",
      vendor: "Stripe",
      logo_url: "https://logo.clearbit.com/stripe.com",
      website_url: "https://stripe.com",
      tags: ["payments", "billing", "fintech"],
      departments: ["finance", "operations"],
      created_at: new Date().toISOString(),
    },
    {
      id: "15",
      name: "Auth0",
      slug: "auth0",
      description:
        "Identity platform for authentication, authorization, and user management.",
      category: "SaaS",
      vendor: "Okta",
      logo_url: "https://logo.clearbit.com/auth0.com",
      website_url: "https://auth0.com",
      tags: ["auth", "identity", "security"],
      departments: ["it", "legal", "engineering"],
      created_at: new Date().toISOString(),
    },
    {
      id: "16",
      name: "Supabase",
      slug: "supabase",
      description:
        "Open-source Firebase alternative with Postgres, auth, storage, and realtime.",
      category: "PaaS",
      vendor: "Supabase",
      logo_url: "https://logo.clearbit.com/supabase.com",
      website_url: "https://supabase.com",
      tags: ["database", "postgres", "backend"],
      departments: none,
      created_at: new Date().toISOString(),
    },
    {
      id: "17",
      name: "HubSpot",
      slug: "hubspot",
      description:
        "CRM and marketing automation for inbound campaigns, email, and lead nurturing.",
      category: "SaaS",
      vendor: "HubSpot",
      logo_url: "https://logo.clearbit.com/hubspot.com",
      website_url: "https://www.hubspot.com",
      tags: ["crm", "marketing", "automation"],
      departments: ["marketing", "customer-support", "operations"],
      created_at: new Date().toISOString(),
    },
    {
      id: "18",
      name: "Greenhouse",
      slug: "greenhouse",
      description:
        "Applicant tracking and hiring workflow software for recruiting teams.",
      category: "SaaS",
      vendor: "Greenhouse Software",
      logo_url: "https://logo.clearbit.com/greenhouse.io",
      website_url: "https://www.greenhouse.com",
      tags: ["ats", "hiring", "hr-tech"],
      departments: ["recruitment", "hr"],
      created_at: new Date().toISOString(),
    },
    {
      id: "19",
      name: "Docebo",
      slug: "docebo",
      description:
        "Learning management system for employee training, onboarding, and compliance courses.",
      category: "SaaS",
      vendor: "Docebo",
      logo_url: "https://logo.clearbit.com/docebo.com",
      website_url: "https://www.docebo.com",
      tags: ["lms", "elearning", "compliance"],
      departments: ["training", "hr", "health-safety"],
      created_at: new Date().toISOString(),
    },
    {
      id: "20",
      name: "SafetyCulture",
      slug: "safetyculture",
      description:
        "Digital checklists, inspections, and incident reporting for frontline safety.",
      category: "SaaS",
      vendor: "SafetyCulture",
      logo_url: "https://logo.clearbit.com/safetyculture.com",
      website_url: "https://safetyculture.com",
      tags: ["safety", "compliance", "inspections"],
      departments: ["health-safety", "site-operations", "operations"],
      created_at: new Date().toISOString(),
    },
    {
      id: "21",
      name: "Workday",
      slug: "workday",
      description:
        "Enterprise cloud suite for HR, payroll, finance, and workforce planning.",
      category: "SaaS",
      vendor: "Workday",
      logo_url: "https://logo.clearbit.com/workday.com",
      website_url: "https://www.workday.com",
      tags: ["hr", "erp", "payroll"],
      departments: ["hr", "finance", "recruitment", "procurement"],
      created_at: new Date().toISOString(),
    },
    ...additionalServices,
  ],
  groups: [
    {
      id: "g1",
      slug: "vulnerability-scanners",
      title: "Vulnerability Scanners",
      description: "Tools for finding, prioritizing, and remediating security vulnerabilities.",
      service_ids: ["1101", "1102", "1103", "1104", "1105", "1106", "1107", "1108"],
      created_at: new Date().toISOString(),
    },
    {
      id: "g8",
      slug: "saas-solutions",
      title: "SaaS Solutions",
      description: "IT operations, cyber security, and compliance software.",
      service_ids: [...SAAS_SOLUTION_IDS],
      collapsible: true,
      default_collapsed: true,
      created_at: new Date().toISOString(),
    },
    {
      id: "g8-it",
      slug: "saas-it",
      parent_slug: "saas-solutions",
      title: "IT",
      description: "Observability, data platforms, and core IT SaaS.",
      service_ids: [...SAAS_IT_IDS],
      created_at: new Date().toISOString(),
    },
    {
      id: "g8-cyber",
      slug: "saas-cyber-security",
      parent_slug: "saas-solutions",
      title: "Cyber Security",
      description: "Endpoint, email, network security, and AppSec tools.",
      service_ids: [...SAAS_CYBER_IDS],
      created_at: new Date().toISOString(),
    },
    {
      id: "g8-compliance",
      slug: "saas-compliance",
      parent_slug: "saas-solutions",
      title: "Compliance",
      description: "GRC, privacy, and audit automation platforms.",
      service_ids: [...SAAS_COMPLIANCE_IDS],
      created_at: new Date().toISOString(),
    },
    {
      id: "g2",
      slug: "compliance-platforms",
      title: "Compliance Platforms",
      description:
        "GRC and compliance automation for SOC 2, ISO 27001, and regulatory programs.",
      service_ids: ["1201", "1202", "1203", "1204", "1205", "1206", "1207", "1208"],
      created_at: new Date().toISOString(),
    },
    {
      id: "g3",
      slug: "cloud-compute-iaas",
      title: "Cloud Compute (IaaS)",
      description: "Virtual machine and bare-metal compute from major clouds.",
      service_ids: ["11", "12", "13", "1001", "1002", "1003", "1004", "1005", "1006", "1007"],
      created_at: new Date().toISOString(),
    },
    {
      id: "g4",
      slug: "developer-platforms",
      title: "Developer Platforms",
      description: "PaaS and backend platforms for shipping apps faster.",
      service_ids: ["9", "10", "16"],
      created_at: new Date().toISOString(),
    },
    {
      id: "g7",
      slug: "paas-platforms",
      title: "PaaS Platforms",
      description:
        "Hyperscaler application, data, integration, and serverless platforms.",
      service_ids: [...PAAS_CLOUD_SERVICE_IDS],
      created_at: new Date().toISOString(),
    },
    {
      id: "g7-aws",
      slug: "paas-aws",
      parent_slug: "paas-platforms",
      title: "AWS",
      description: "Amazon Web Services PaaS offerings.",
      service_ids: [...PAAS_AWS_IDS],
      created_at: new Date().toISOString(),
    },
    {
      id: "g7-azure",
      slug: "paas-azure",
      parent_slug: "paas-platforms",
      title: "Azure",
      description: "Microsoft Azure PaaS offerings.",
      service_ids: [...PAAS_AZURE_IDS],
      created_at: new Date().toISOString(),
    },
    {
      id: "g7-gcp",
      slug: "paas-gcp",
      parent_slug: "paas-platforms",
      title: "Google Cloud",
      description: "Google Cloud Platform PaaS offerings.",
      service_ids: [...PAAS_GCP_IDS],
      created_at: new Date().toISOString(),
    },
    {
      id: "g5",
      slug: "generative-ai",
      title: "Generative AI",
      description: "Leading LLMs, copilots, and creative AI platforms.",
      service_ids: ["901", "902", "903", "904", "905", "906", "907", "908", "909", "910", "911", "912"],
      created_at: new Date().toISOString(),
    },
    {
      id: "g6",
      slug: "marketing-stack",
      title: "Marketing Stack",
      description: "CRM, analytics, design, and campaign tools for growth teams.",
      service_ids: ["201", "213", "214", "218", "219", "220", "222"],
      created_at: new Date().toISOString(),
    },
  ],
};
