import type { CatalogData } from "@/types";

/** Demo catalog when Supabase env vars are not set (local dev / preview). */
export const fallbackCatalog: CatalogData = {
  services: [
    {
      id: "1",
      name: "Snowflake",
      slug: "snowflake",
      description:
        "Cloud data platform for warehousing, analytics, and secure data sharing at scale.",
      category: "SaaS",
      vendor: "Snowflake Inc.",
      logo_url: "https://logo.clearbit.com/snowflake.com",
      website_url: "https://www.snowflake.com",
      tags: ["data-warehouse", "analytics", "sql"],
      created_at: new Date().toISOString(),
    },
    {
      id: "2",
      name: "BigQuery",
      slug: "bigquery",
      description:
        "Serverless, highly scalable multi-cloud data warehouse built for analytics.",
      category: "SaaS",
      vendor: "Google Cloud",
      logo_url: "https://logo.clearbit.com/cloud.google.com",
      website_url: "https://cloud.google.com/bigquery",
      tags: ["data-warehouse", "analytics", "serverless"],
      created_at: new Date().toISOString(),
    },
    {
      id: "3",
      name: "Amazon Redshift",
      slug: "amazon-redshift",
      description:
        "Fully managed petabyte-scale cloud data warehouse for analytics workloads.",
      category: "SaaS",
      vendor: "AWS",
      logo_url: "https://logo.clearbit.com/aws.amazon.com",
      website_url: "https://aws.amazon.com/redshift/",
      tags: ["data-warehouse", "analytics", "aws"],
      created_at: new Date().toISOString(),
    },
    {
      id: "4",
      name: "Databricks",
      slug: "databricks",
      description:
        "Lakehouse platform unifying data engineering, analytics, and machine learning.",
      category: "PaaS",
      vendor: "Databricks",
      logo_url: "https://logo.clearbit.com/databricks.com",
      website_url: "https://www.databricks.com",
      tags: ["lakehouse", "spark", "ml"],
      created_at: new Date().toISOString(),
    },
    {
      id: "5",
      name: "Datadog",
      slug: "datadog",
      description:
        "Observability platform for metrics, logs, traces, and security monitoring.",
      category: "SaaS",
      vendor: "Datadog",
      logo_url: "https://logo.clearbit.com/datadoghq.com",
      website_url: "https://www.datadoghq.com",
      tags: ["monitoring", "apm", "observability"],
      created_at: new Date().toISOString(),
    },
    {
      id: "6",
      name: "Grafana Cloud",
      slug: "grafana-cloud",
      description:
        "Managed observability stack for metrics, logs, traces, and dashboards.",
      category: "SaaS",
      vendor: "Grafana Labs",
      logo_url: "https://logo.clearbit.com/grafana.com",
      website_url: "https://grafana.com/products/cloud/",
      tags: ["monitoring", "dashboards", "observability"],
      created_at: new Date().toISOString(),
    },
    {
      id: "7",
      name: "New Relic",
      slug: "new-relic",
      description:
        "Full-stack observability with APM, infrastructure monitoring, and logs.",
      category: "SaaS",
      vendor: "New Relic",
      logo_url: "https://logo.clearbit.com/newrelic.com",
      website_url: "https://newrelic.com",
      tags: ["monitoring", "apm", "observability"],
      created_at: new Date().toISOString(),
    },
    {
      id: "8",
      name: "Prometheus",
      slug: "prometheus",
      description:
        "Open-source systems monitoring and alerting toolkit with a dimensional data model.",
      category: "SaaS",
      vendor: "CNCF",
      logo_url: "https://cdn.simpleicons.org/prometheus/E6522C",
      website_url: "https://prometheus.io",
      tags: ["monitoring", "metrics", "open-source"],
      created_at: new Date().toISOString(),
    },
    {
      id: "9",
      name: "Vercel",
      slug: "vercel",
      description:
        "Frontend cloud for deploying and scaling Jamstack and full-stack web apps.",
      category: "PaaS",
      vendor: "Vercel",
      logo_url: "https://logo.clearbit.com/vercel.com",
      website_url: "https://vercel.com",
      tags: ["hosting", "serverless", "edge"],
      created_at: new Date().toISOString(),
    },
    {
      id: "10",
      name: "Heroku",
      slug: "heroku",
      description:
        "PaaS for building, running, and scaling applications in multiple languages.",
      category: "PaaS",
      vendor: "Salesforce",
      logo_url: "https://logo.clearbit.com/heroku.com",
      website_url: "https://www.heroku.com",
      tags: ["hosting", "paas", "containers"],
      created_at: new Date().toISOString(),
    },
    {
      id: "11",
      name: "AWS EC2",
      slug: "aws-ec2",
      description:
        "Scalable virtual servers in the cloud for compute-intensive workloads.",
      category: "IaaS",
      vendor: "AWS",
      logo_url: "https://logo.clearbit.com/aws.amazon.com",
      website_url: "https://aws.amazon.com/ec2/",
      tags: ["compute", "vms", "aws"],
      created_at: new Date().toISOString(),
    },
    {
      id: "12",
      name: "Google Compute Engine",
      slug: "google-compute-engine",
      description:
        "High-performance virtual machines running on Google's global infrastructure.",
      category: "IaaS",
      vendor: "Google Cloud",
      logo_url: "https://logo.clearbit.com/cloud.google.com",
      website_url: "https://cloud.google.com/compute",
      tags: ["compute", "vms", "gcp"],
      created_at: new Date().toISOString(),
    },
    {
      id: "13",
      name: "Azure Virtual Machines",
      slug: "azure-virtual-machines",
      description:
        "On-demand scalable compute capacity with Windows and Linux VMs.",
      category: "IaaS",
      vendor: "Microsoft Azure",
      logo_url: "https://logo.clearbit.com/azure.microsoft.com",
      website_url: "https://azure.microsoft.com/products/virtual-machines",
      tags: ["compute", "vms", "azure"],
      created_at: new Date().toISOString(),
    },
    {
      id: "14",
      name: "Stripe",
      slug: "stripe",
      description:
        "Payments infrastructure for the internet — APIs for billing and subscriptions.",
      category: "SaaS",
      vendor: "Stripe",
      logo_url: "https://logo.clearbit.com/stripe.com",
      website_url: "https://stripe.com",
      tags: ["payments", "billing", "fintech"],
      created_at: new Date().toISOString(),
    },
    {
      id: "15",
      name: "Auth0",
      slug: "auth0",
      description:
        "Identity platform for authentication, authorization, and user management.",
      category: "SaaS",
      vendor: "Okta",
      logo_url: "https://logo.clearbit.com/auth0.com",
      website_url: "https://auth0.com",
      tags: ["auth", "identity", "security"],
      created_at: new Date().toISOString(),
    },
    {
      id: "16",
      name: "Supabase",
      slug: "supabase",
      description:
        "Open-source Firebase alternative with Postgres, auth, storage, and realtime.",
      category: "PaaS",
      vendor: "Supabase",
      logo_url: "https://logo.clearbit.com/supabase.com",
      website_url: "https://supabase.com",
      tags: ["database", "postgres", "backend"],
      created_at: new Date().toISOString(),
    },
  ],
  groups: [
    {
      id: "g1",
      slug: "alternatives-to-snowflake",
      title: "Alternatives to Snowflake",
      description: "Comparable cloud data warehouses and lakehouse platforms.",
      service_ids: ["1", "2", "3", "4"],
      created_at: new Date().toISOString(),
    },
    {
      id: "g2",
      slug: "best-monitoring-tools",
      title: "Best Monitoring Tools",
      description: "Top observability and monitoring platforms for modern stacks.",
      service_ids: ["5", "6", "7", "8"],
      created_at: new Date().toISOString(),
    },
    {
      id: "g3",
      slug: "cloud-compute-iaas",
      title: "Cloud Compute (IaaS)",
      description: "Virtual machine and bare-metal compute from major clouds.",
      service_ids: ["11", "12", "13"],
      created_at: new Date().toISOString(),
    },
    {
      id: "g4",
      slug: "developer-platforms",
      title: "Developer Platforms",
      description: "PaaS and backend platforms for shipping apps faster.",
      service_ids: ["9", "10", "16"],
      created_at: new Date().toISOString(),
    },
  ],
};
