import { createService } from "@/lib/catalog/service-factory";
import type { PaasProvider } from "@/lib/paas-providers";
import type { CloudService } from "@/types";

function paas(
  id: string,
  name: string,
  description: string,
  vendor: string,
  websiteUrl: string,
  tags: string[],
  provider: PaasProvider,
  slug?: string,
): CloudService {
  return createService(id, name, description, vendor, websiteUrl, tags, {
    category: "PaaS",
    paas_provider: provider,
    slug,
  });
}

export const PAAS_AWS_IDS = [
  "1301",
  "1302",
  "1303",
  "1304",
  "1305",
  "1306",
  "1307",
  "1308",
  "1309",
] as const;

export const PAAS_AZURE_IDS = [
  "1310",
  "1311",
  "1312",
  "1313",
  "1314",
  "1315",
  "1316",
  "1317",
  "1318",
  "1319",
  "1320",
] as const;

export const PAAS_GCP_IDS = [
  "1321",
  "1322",
  "1323",
  "1324",
  "1325",
  "1326",
  "1327",
  "1328",
  "1329",
  "1330",
  "1331",
] as const;

export const PAAS_CLOUD_SERVICE_IDS = [
  ...PAAS_AWS_IDS,
  ...PAAS_AZURE_IDS,
  ...PAAS_GCP_IDS,
];

export const paasCloudServices: CloudService[] = [
  paas(
    "1301",
    "AWS Elastic Beanstalk",
    "Deploy and scale web applications without managing the underlying infrastructure.",
    "AWS",
    "https://aws.amazon.com/elasticbeanstalk/",
    ["app-hosting", "containers", "deploy"],
    "aws",
    "aws-elastic-beanstalk",
  ),
  paas(
    "1302",
    "AWS App Runner",
    "Fully managed service to build and run containerized web apps and APIs at scale.",
    "AWS",
    "https://aws.amazon.com/apprunner/",
    ["containers", "serverless", "apis"],
    "aws",
  ),
  paas(
    "1303",
    "Amazon RDS",
    "Managed relational databases for MySQL, PostgreSQL, MariaDB, Oracle, and SQL Server.",
    "AWS",
    "https://aws.amazon.com/rds/",
    ["database", "sql", "managed"],
    "aws",
    "amazon-rds",
  ),
  paas(
    "1304",
    "Amazon Aurora",
    "MySQL- and PostgreSQL-compatible relational database built for the cloud.",
    "AWS",
    "https://aws.amazon.com/rds/aurora/",
    ["database", "sql", "high-availability"],
    "aws",
  ),
  paas(
    "1305",
    "Amazon DynamoDB",
    "Serverless NoSQL database for single-digit millisecond performance at any scale.",
    "AWS",
    "https://aws.amazon.com/dynamodb/",
    ["database", "nosql", "serverless"],
    "aws",
  ),
  paas(
    "1306",
    "AWS Step Functions",
    "Visual workflows to coordinate distributed applications and microservices.",
    "AWS",
    "https://aws.amazon.com/step-functions/",
    ["workflow", "orchestration", "serverless"],
    "aws",
  ),
  paas(
    "1307",
    "Amazon EventBridge",
    "Serverless event bus to connect applications with event-driven architectures.",
    "AWS",
    "https://aws.amazon.com/eventbridge/",
    ["events", "integration", "serverless"],
    "aws",
  ),
  paas(
    "1308",
    "AWS Lambda",
    "Run code without provisioning servers—pay only for compute time consumed.",
    "AWS",
    "https://aws.amazon.com/lambda/",
    ["serverless", "functions", "compute"],
    "aws",
  ),
  paas(
    "1309",
    "AWS Amplify",
    "Full-stack development platform for building and hosting web and mobile apps.",
    "AWS",
    "https://aws.amazon.com/amplify/",
    ["full-stack", "hosting", "mobile"],
    "aws",
  ),
  paas(
    "1310",
    "Azure App Service",
    "Fully managed platform for building, deploying, and scaling web apps and APIs.",
    "Microsoft Azure",
    "https://azure.microsoft.com/products/app-service",
    ["app-hosting", "web", "apis"],
    "azure",
  ),
  paas(
    "1311",
    "Azure Spring Apps",
    "Managed Spring Boot and Spring Cloud service without operating infrastructure.",
    "Microsoft Azure",
    "https://azure.microsoft.com/products/spring-apps",
    ["spring", "java", "microservices"],
    "azure",
  ),
  paas(
    "1312",
    "Azure Container Apps",
    "Serverless containers for microservices and event-driven applications on Azure.",
    "Microsoft Azure",
    "https://azure.microsoft.com/products/container-apps",
    ["containers", "serverless", "kubernetes"],
    "azure",
  ),
  paas(
    "1313",
    "Azure SQL Database",
    "Fully managed SQL database with built-in intelligence and scalability.",
    "Microsoft Azure",
    "https://azure.microsoft.com/products/azure-sql/database",
    ["database", "sql", "managed"],
    "azure",
  ),
  paas(
    "1314",
    "Azure Cosmos DB",
    "Globally distributed, multi-model NoSQL database for mission-critical apps.",
    "Microsoft Azure",
    "https://azure.microsoft.com/products/cosmos-db",
    ["database", "nosql", "global"],
    "azure",
  ),
  paas(
    "1315",
    "Azure Database for PostgreSQL and MySQL",
    "Managed PostgreSQL and MySQL with high availability, backups, and scaling on Azure.",
    "Microsoft Azure",
    "https://azure.microsoft.com/products/postgresql",
    ["database", "postgresql", "mysql"],
    "azure",
    "azure-database-postgresql-mysql",
  ),
  paas(
    "1316",
    "Azure Logic Apps",
    "Low-code integration and workflow automation across cloud and on-premises systems.",
    "Microsoft Azure",
    "https://azure.microsoft.com/products/logic-apps",
    ["workflow", "integration", "automation"],
    "azure",
  ),
  paas(
    "1317",
    "Azure Service Bus",
    "Enterprise message broker for decoupling applications and services.",
    "Microsoft Azure",
    "https://azure.microsoft.com/products/service-bus",
    ["messaging", "queues", "integration"],
    "azure",
  ),
  paas(
    "1318",
    "Azure Functions",
    "Event-driven serverless compute with automatic scaling and pay-per-execution.",
    "Microsoft Azure",
    "https://azure.microsoft.com/products/functions",
    ["serverless", "functions", "compute"],
    "azure",
  ),
  paas(
    "1319",
    "Azure API Management",
    "Publish, secure, transform, and analyze APIs across environments.",
    "Microsoft Azure",
    "https://azure.microsoft.com/products/api-management",
    ["api-gateway", "apis", "integration"],
    "azure",
  ),
  paas(
    "1320",
    "Azure DevOps Services",
    "Repos, pipelines, boards, and artifacts for planning and shipping software.",
    "Microsoft Azure",
    "https://azure.microsoft.com/products/devops",
    ["devops", "ci-cd", "agile"],
    "azure",
    "azure-devops-services",
  ),
  paas(
    "1321",
    "Google App Engine",
    "Fully managed serverless platform for web apps and APIs at any scale.",
    "Google Cloud",
    "https://cloud.google.com/appengine",
    ["app-hosting", "serverless", "paas"],
    "gcp",
    "google-app-engine",
  ),
  paas(
    "1322",
    "Cloud Run",
    "Run stateless containers on a fully managed platform with automatic scaling.",
    "Google Cloud",
    "https://cloud.google.com/run",
    ["containers", "serverless", "knative"],
    "gcp",
  ),
  paas(
    "1323",
    "Firebase",
    "App development platform with hosting, auth, realtime data, and serverless backends.",
    "Google Cloud",
    "https://firebase.google.com",
    ["mobile", "hosting", "backend"],
    "gcp",
  ),
  paas(
    "1324",
    "Cloud SQL",
    "Fully managed MySQL, PostgreSQL, and SQL Server databases on Google Cloud.",
    "Google Cloud",
    "https://cloud.google.com/sql",
    ["database", "sql", "managed"],
    "gcp",
  ),
  paas(
    "1325",
    "Firestore",
    "Serverless NoSQL document database for mobile, web, and server development.",
    "Google Cloud",
    "https://cloud.google.com/firestore",
    ["database", "nosql", "serverless"],
    "gcp",
  ),
  paas(
    "1326",
    "Bigtable",
    "Fully managed wide-column NoSQL database for large analytical and operational workloads.",
    "Google Cloud",
    "https://cloud.google.com/bigtable",
    ["database", "nosql", "big-data"],
    "gcp",
  ),
  paas(
    "1327",
    "Cloud Functions",
    "Event-driven functions that scale automatically—pay only while your code runs.",
    "Google Cloud",
    "https://cloud.google.com/functions",
    ["serverless", "functions", "compute"],
    "gcp",
  ),
  paas(
    "1328",
    "Cloud Workflows",
    "Orchestrate and automate Google Cloud and HTTP-based services with serverless workflows.",
    "Google Cloud",
    "https://cloud.google.com/workflows",
    ["workflow", "orchestration", "automation"],
    "gcp",
  ),
  paas(
    "1329",
    "Apigee",
    "API management platform for designing, securing, and scaling APIs and AI products.",
    "Google Cloud",
    "https://cloud.google.com/apigee",
    ["api-management", "apis", "gateway"],
    "gcp",
  ),
  paas(
    "1330",
    "Cloud Endpoints",
    "Develop, deploy, and manage APIs on Google Cloud with OpenAPI support.",
    "Google Cloud",
    "https://cloud.google.com/endpoints",
    ["apis", "openapi", "gateway"],
    "gcp",
  ),
  paas(
    "1331",
    "Artifact Registry",
    "Universal package manager for container images, language packages, and OS artifacts.",
    "Google Cloud",
    "https://cloud.google.com/artifact-registry",
    ["artifacts", "containers", "registry"],
    "gcp",
  ),
];
